### ISSUE TITLE
Ship text transformer in WASM

### ISSUE THREAD

**Issue by DawChihLiou** [tantaraio/voy#1]
Using a Rust wrapper of [ONNX](https://onnxruntime.ai). 

- Candidate: [ort](https://github.com/pykeio/ort)

**Comment by jlarmstrongiv** [comment]
I only know of two popular libraries to handle running wasm via rust:
- [wasmer](https://github.com/wasmerio/wasmer)
- [wasmtime](https://github.com/bytecodealliance/wasmtime)

Though, I don’t know if either of those two libraries will allow you to pack the transformer.

**Comment by maccman** [comment]
I'm not convinced that packing the transformers in is a good idea. I seems like everyone's going to want to use different libraries and have different needs. A couple of examples probably will suffice.

**Comment by DawChihLiou** [comment]
> I'm not convinced that packing the transformers in is a good idea. I seems like everyone's going to want to use different libraries and have different needs. A couple of examples probably will suffice.

Absolutely. The idea is to pack a language model runtime like onnx so everyone can choose their own models to perform feature extraction. Voy will be a standalone semantic engine with this feature in place. It's worth exploring too because I have a feeling the wasm transformer will be more performant than js.

**Comment by DawChihLiou** [comment]
onnnxruntime-web performance issue: https://github.com/microsoft/onnxruntime/issues/11181
