### ISSUE TITLE
Support index update

### ISSUE THREAD

**Issue by DawChihLiou** [tantaraio/voy#3]
Currently kd-tree doesn't support updates. Would like to find a performant k-d tree replacement that supports

- add
- remove
- serde

### Candidates

- https://github.com/sdd/kiddo
- https://github.com/dimforge/nalgebra

**Comment by mjp0** [comment]
Since this was moved to a backlog, can you give any estimate when this might be realistically landing to voy? The reason I'm asking is that I'm building something where voy could be very useful, but for performance reasons, updating index is a bit of a requirement. Awesome project in any case!

**Comment by jlarmstrongiv** [comment]
I’ll definitely switch to voy once this feature lands 😄 it’s a drawback I’ve been trying to avoid with other libraries

**Comment by DawChihLiou** [comment]
https://github.com/sdd/kiddo/issues/43

**Comment by DawChihLiou** [comment]
Published in [v0.2.0](https://www.npmjs.com/package/voy-search)

**Comment by DawChihLiou** [comment]
@mjp0 @jlarmstrongiv index update is now available in Voy! Check it out and let me know what you think. Any feedback is appreciated !

**Comment by jlarmstrongiv** [comment]
@DawChihLiou that’s great to hear!  Voy being both serializable and updatable is awesome.  The only blocker is now https://github.com/tantaraio/voy/issues/21

**Comment by DawChihLiou** [comment]
> @DawChihLiou that’s great to hear! Voy being both serializable and updatable is awesome. The only blocker is now #21

#21 is addressed. I replaced the k-d tree implementation with [kiddo](https://github.com/sdd/kiddo) and the query result is aligned with the case study in the issue.
