### ISSUE TITLE
Feature request: remove resource by id 

### ISSUE THREAD

**Issue by ocavue** [tantaraio/voy#44]
Currently `Voy.remove()` API requires a full `resource` to work. We have to store the whole resource (including the `embeddings` array) somewhere so whtat we can do the deletion later. It would be great if we can just delete a resource by giving an id string.

**Comment by DawChihLiou** [comment]
Hey @ocavue thanks for the issue! Currently `remove()` needs the embeddings. Voy uses the embeddings as coordinates to index the resources at the moment but I'm looking into other data structure to replace the current index. 

Voy doesn't store the embeddings so having your own storage layer might be the best solution at the moment.
