### ISSUE TITLE
Is heavy usage possible?

### ISSUE THREAD

**Issue by maxbaluev** [tantaraio/voy#46]
Hi all, I'm making a Chrome extension that saves all text content that a user looks at. Next I want to use voy to create embeddings and write an algorithm to make context for gpt. Can you tell me what difficulties I might encounter? Perhaps too much data, or will the speed be slow? Also, is it works fine in web/service workers?

**Comment by DawChihLiou** [comment]
Hey @maxbaluev thanks for reaching out! It's possible. Voy works with workers. Data storage will depend on the limitation of the storage you choose, for example [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#web_storage), and the transformer model you choose. 

Currently Voy only support embedding index. It doesn't store the embeddings but instead use the embeddings as coordinates to locate data and enable faster retrievals, like database index conceptually.

I'm currently looking for sponsors to kickoff the project to provide native Wasm transformers in Voy to tackle the performance issue in most of the JavaScript based transformers. At the mean time, libraries like [transformers.js](https://github.com/xenova/transformers.js/) or [web-ai](https://github.com/visheratin/web-ai) are great options for web to handling the text feature extraction.

**Comment by maxbaluev** [comment]
Is it true that indexes are only stored in memory, and the storage layer is managed by me ? Will it work with embeddings from openai?

**Comment by DawChihLiou** [comment]
That's correct. Voy doesn't store embeddings and you have full control over the storage solution. Voy also exposes serialize and deserialize functions so you can also store the serialized indexes in your storage layer. 

Looking at [OpenAI's documentation](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings), the embeddings should work with Voy just fine. I think you're the first to experiment Voy with OpenAI. I'm very excited about what you're about to build!
