### ISSUE TITLE
Index serialization

### ISSUE THREAD

**Issue by visheratin** [tantaraio/voy#5]
How can I persist the index after building it? I'm building a browser extension and want to save the index in the browser storage for future use.

**Comment by DawChihLiou** [comment]
Hey @visheratin, thanks for your question! `voy.index()` returns a serialized index as a string. It's compatible with local storage and it should cover your use case.

**Comment by josephrocca** [comment]
@DawChihLiou should it return a blob instead? Strings have a relatively low maximum size in most browsers IIRC - it's several hundred MB, but an index could potentially grow much larger than that and still run performantly in the browser.
